language: node_js

node_js:
  - '0.12'
  - '0.10'
sudo: false # Enable docker-based containers
cache:
  directories: # Cache dependencies
    - node_modules

script:
  - npm test

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database koopdev;' -U postgres
  - psql -c 'create extension postgis;' -U postgres
